[[linter]]
code = 'RUSTFMT'
include_patterns = ['**/*.rs']
command = [
    'python',
    'examples/rustfmt_linter.py',
    '--binary=rustfmt',
    '--config-path=rustfmt.toml',
    '--',
    '@{{PATHSFILE}}'
]
